# Generated by Django 3.1.1 on 2020-11-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('partnerCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('loyaltyPrograms', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('loyaltyProgramId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('loyaltyProgramName', models.CharField(max_length=50)),
                ('loyaltyCurrencyName', models.CharField(default='SGD', max_length=50)),
                ('processingTime', models.CharField(default='1 day', max_length=50)),
                ('description', models.CharField(default='description', max_length=50)),
                ('enrollmentLink', models.CharField(default='test.com', max_length=50)),
                ('termsAndConditionsLink', models.CharField(default='test.com', max_length=50)),
                ('ratio', models.IntegerField(default=10, help_text='Ratio of bank points to loyalty program points')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('referenceNumber', models.CharField(max_length=50)),
                ('membershipNumber', models.CharField(max_length=50)),
                ('partnerCode', models.CharField(max_length=50)),
                ('transactionDate', models.CharField(max_length=50)),
                ('transferAmount', models.CharField(max_length=50)),
                ('additionalInfo', models.CharField(blank=True, max_length=50)),
                ('outcomeCode', models.CharField(blank=True, max_length=50, null=True)),
                ('loyaltyProgramId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('partnerCode', models.CharField(max_length=50)),
                ('pointBalance', models.CharField(default=10000, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('loyaltyProgramId', models.CharField(max_length=50)),
                ('membershipNumber', models.CharField(max_length=50)),
                ('loyaltyMembershipRef', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='User ID')),
            ],
        ),
    ]
